apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: echo-app
  labels:
    app: echo-app
    tier: echo-app
spec:
  replicas: 4
  selector:
    matchLabels:
      tier: echo-app
  template:
    metadata:
      labels:
        tier: echo-app
    spec:
      containers:
      - name: echo-app
        image:  yanissdu33/wik-dps-tp02:latest
        ports:
        - containerPort: 8080